name: Haskell CI

on:
  push:
    branches: [ "hs" ]
  pull_request:
    branches: [ "hs" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.ghcup
          dist-newstyle
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.4'
        cabal-version: '3.6'


    - name: Install dependencies
      run: cabal build

    - name: Run tests
      run: cabal test
